[package]
name = "dioxus-use-mounted"
description = "Material design UI for Dioxus"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
dioxus = { version = "0.4" }
dioxus-signals = { version = "0.4" }
dioxus-web = { version = "0.4" }
